### ISSUE TITLE
Доработки: map

### ISSUE THREAD

**Issue by slogger** [sipayRT/hackaton#17]
Я наконец снова добрался до кода
### Что сделал:
- [x] Разобрался с _инфраструктурой_ (не очень красиво, но работает)
- [x] Переименовал блок ymaps -> map-helper
- [x] Добавил стандартное значение zoom
- [x] **(ymaps)** Добавил возможность указывать тип карты
- [x] **(ymaps)** Теперь геообъекты поддерживают все свои опции из апи в bemjson'e
- [x] Разбил примеры, по _вендорному_ признаку
### Что нужно сделать
- [ ] Покрыть код тестами
- [ ] Написать документацию
- [ ] Доделать подключение google maps
- [ ] bh шаблон
### С чем испытываю проблемы
- [ ] Загрузка API Google Maps, 
  Отправляю правильный урл в loader_type_js
  получаю в ответ ошибку

```
     Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened. 
```
- [ ] Еще мне не очень нравится как сделан map.bemhtml, есть идеи как сделать красивее

**Comment by sipayRT** [comment]
а сам код где?

**Comment by slogger** [comment]
@sipayRT https://github.com/sipayRT/hackaton/tree/map

**Comment by sipayRT** [comment]
@slogger сразу PR отправь и разрабатывайся дальше - там удобней смотреть на код, который ти пишешь. Сейчас сложно отследить твою работу

**Comment by sipayRT** [comment]
только не забудь, что PR нужно добавить именно в моем форке ;)

**Comment by sipayRT** [comment]
moved to https://github.com/bem-incubator/hackaton/issues/2
