### ISSUE TITLE
Перенести в организацию bem-incubator

### ISSUE THREAD

**Issue by aristov** [sipayRT/hackaton#19]

**Comment by sipayRT** [comment]
Как будем переносить? Сделаем отдельную библиотеку с новыми блоками и подключим туда bem-components?

**Comment by aristov** [comment]
Похоже, что у нас есть 2 варианта:
1. сделаем отдельную библиотеку с новыми блоками и подключим туда bem-components
2. перенесем как есть и удалим блоки которые уже есть в bem-components

В первом случае мы теряем оригинальные хакатоновские коммиты и получаем весь код в одном первоначальном коммите, нужно будет настроить инфраструктуру заново. 
Во втором вся история сохраняется, но вместе с ней еще приедет много лишней истории про bem-components. Кроме того, это будет отображаться как форк, но зато вся инфраструктура унаследуется и не нужно будет ничего настраивать.

На мой взгляд первый вариант все же предпочтительнее, хоть и предполагает немного больше работы (код про инфраструктуру можно будет просто скопировать вместе с блоками).

сс @tadatuta

**Comment by aristov** [comment]
Блок `calendar` можно сразу унести в bem-calendar.

**Comment by tadatuta** [comment]
я за новую библиотеку и за библиотеку `bem-date` вместо `bem-calendar`

**Comment by sipayRT** [comment]
@tadatuta я тоже за новую библиотеку. А вот насчет `bem-date` - я против. Название больше относится ко времени, а не к календарю. Кстати, я изначально ее так занвал и сразу получил ~~по голове~~ ссылку от Ваарнкина с уже готовой либой про форматирование даты. Это говорит о том, что название не однозначное.

**Comment by tadatuta** [comment]
@sipayRT так я как раз о том, чтобы собрать в этой библиотеке вообще все про даты, а не только про календарь. В том числе и форматирование дат, да.

**Comment by aristov** [comment]
> ссылку от Ваарнкина с уже готовой либой про форматирование даты

хотелось бы взглянуть

**Comment by tadatuta** [comment]
https://github.com/narqo/bem-time

**Comment by sipayRT** [comment]
https://github.com/bem-incubator/hackaton

**Comment by aristov** [comment]
:+1:
